# Generated by Django migrations

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(default='edge01', max_length=50)),
                ('building', models.CharField(default='gedungA', max_length=50)),
                ('command_type', models.CharField(choices=[('fan_on', 'Turn Fan On'), ('fan_off', 'Turn Fan Off'), ('reset_sensor', 'Reset Sensor'), ('calibrate', 'Calibrate Sensor'), ('reboot', 'Reboot Device'), ('update_threshold', 'Update Threshold')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(default='edge01', max_length=50)),
                ('building', models.CharField(default='gedungA', max_length=50)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('warning', 'Warning'), ('offline', 'Offline')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('temperature', 'Temperature (°C)'), ('humidity', 'Humidity (%)'), ('light', 'Light (lumens)'), ('co2', 'CO2 (ppm)')], max_length=20)),
                ('device', models.CharField(default='edge01', max_length=50)),
                ('building', models.CharField(default='gedungA', max_length=50)),
                ('value', models.FloatField()),
                ('event', models.CharField(choices=[('threshold_exceeded', 'Threshold Exceeded'), ('threshold_below', 'Threshold Below'), ('anomaly_detected', 'Anomaly Detected'), ('sensor_error', 'Sensor Error')], max_length=30)),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('temperature', 'Temperature (°C)'), ('humidity', 'Humidity (%)'), ('light', 'Light (lumens)'), ('co2', 'CO2 (ppm)')], max_length=20)),
                ('device', models.CharField(default='edge01', max_length=50)),
                ('building', models.CharField(default='gedungA', max_length=50)),
                ('value', models.FloatField()),
                ('avg', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sensorstate',
            index=models.Index(fields=['sensor', 'device', '-timestamp'], name='monitoring_s_sensor_4a5c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorstate',
            index=models.Index(fields=['-timestamp'], name='monitoring_s_timesta_e73b88_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorevent',
            index=models.Index(fields=['sensor', 'device', '-timestamp'], name='monitoring_s_sensor_a777dc_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorevent',
            index=models.Index(fields=['level', '-timestamp'], name='monitoring_s_level_4e7b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorevent',
            index=models.Index(fields=['acknowledged', '-timestamp'], name='monitoring_s_acknowl_140a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['device', '-timestamp'], name='monitoring_h_device_8b0fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['status', '-timestamp'], name='monitoring_h_status_636c8c_idx'),
        ),
    ]